### ISSUE TITLE
Attempting to run multiple directories at once ignores other options

### ISSUE THREAD

**Issue by dannycbowman** [ajakef/gemlog#47]
When you have a directory with multiple subdirectories containing raw Gem files and you do:

gemconvert -i * -o uncorrected_sac/ -f sac

The -o and -f options are ignored.  The output is:

gork:raw dbowma$ gemconvert -i * -o uncorrected_sac/ -f sac
gemlog version 1.7.2
inputdir  ANTO
serial numbers  ['308']
outputdir  mseed

Not a huge deal, I set up a bash loop to go through the subdirectories, but maybe worth fixing if it's simple.

**Comment by ajakef** [comment]
Thanks for raising this. I looked into what it would take to fix it and from what I see, it does not appear to be a simple fix. Since it isn't a very common situation and is handled easily with a bash loop or simply running multiple processes in different terminals (I occasionally need to do these things myself), I can't justify spending the time on this it would require. I'm closing the issue as "not planned" and will clarify in the gemconvert help page that -i must refer to a single folder, but if someone wants to work on it, I would accept a PR that fixes it and includes an automated test in the 'tests/' folder.
