### ISSUE TITLE
Code style does not follow common python standards

### ISSUE THREAD

**Issue by ajakef** [ajakef/gemlog#5]
e.g., functions should be lower_with_underscores, but are currently CapWords (which should be reserved for classes). There are probably issues with long lines, spacing, and other things that might decrease readability to experienced python users.

This will break back-compatibility and should be done soon before the number of users increases.

https://www.python.org/dev/peps/pep-0008/
https://namingconvention.org/python/

**Comment by kevinsa5** [comment]
+1 to following PEP8, although I suggest taking advantage of the concession it makes in the [Line Length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) section about increasing the character limit from 79 to 99 characters -- I frequently find myself reformatting code in a silly way to keep below 80 characters.  

I also suggest thinking about two formatting issues separately -- (1) getting the existing codebase into compliance and (2) enforcing standards on new additions. 

For new code there are a handful of free linters out there that will automatically check github PRs as one of the CI checks.  pvlib uses [stickler ci](https://stickler-ci.com/) which adds comments to PRs about style issues, e.g.:

![image](https://user-images.githubusercontent.com/2515508/91239649-655e1380-e6fd-11ea-86e2-c5b01e1a501a.png)

For the existing code, you could reformat by hand or use an automated tool.  One such tool is [black](https://black.readthedocs.io/en/stable/), which I see lots of people talking about but not as many people using.  It will reformat your code in-place for you instead of just complaining about it.  If it were me I'd probably reformat by hand, guided by a linter like `flake8` or similiar.

**Comment by ajakef** [comment]
The function/class naming issue is mostly resolved now (version 1.0.0) with the old, non-compliant names left as aliases temporarily so nobody's code should break.

Still need to add a linter to the github CI checks.

**Comment by ajakef** [comment]
A linter was added to the CI months ago, so this is basically done.

**Comment by ajakef** [comment]
A linter was added to the CI months ago, so this is basically done.
