### ISSUE TITLE
docstrings are still needed for most functions

### ISSUE THREAD

**Issue by ajakef** [ajakef/gemlog#9]

**Comment by kevinsa5** [comment]
The majority of well-documented python packages use sphinx [1] to build HTML docs to host on GH Pages or ReadTheDocs.  And the majority of scientific python packages use numpy-style docstrings [2] with sphinx's napoleon [3] plugin to automatically generate API documentation.  The results end up looking like this: https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.temperature.faiman.html#pvlib.temperature.faiman

I vote for numpy-style docstrings, not only because they are a step towards online docs, but also because IMHO they are much more readable than the default sphinx style and better than the google style too. 

[1] https://www.sphinx-doc.org/en/master/
[2] https://numpydoc.readthedocs.io/en/latest/format.html
[3] https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
